### ISSUE TITLE
There are some improvement or new features

### ISSUE THREAD

**Issue by Malkhan52** [BSenthamizhSelvan/MM.SummerTask.2018#2]
No doubt u did good job but still there are some features need to be there:-

- Poll question

- Ask a question

- Forum

- commenting

Now in admin panel:-

- while editing article image name or image should be visible(bcoz now u have its name so it's easy to view image)

- category and Author name should be selected

-answer for ask a question

- comment approval, editing, deleting (while showing comment in admin panel comment content should be with post title so we can identify the post.)

**Comment by BSenthamizhSelvan** [comment]
Fixed
